### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mamen** [ugml/api#30]
Requirements:

- automatic testing of all routes
- code-coverage > 80%

**Comment by Phoscur** [comment]
related: !36

**Comment by Phoscur** [comment]
Add a travis badge to motivate your test coverage target!

**Comment by mamen** [comment]
i initialy wanted to build a travis-pipeline with automatic deployment, but as you've told me about github actions recently, i might consider to use travis "just" for testing and switch to github actions once they are available/i am a beta-tester

**Comment by mamen** [comment]
Added travis-config in PR #42

**Comment by Phoscur** [comment]
To fix test watch mode `npm run test-watch` the mocha --exit flag needs to be removed from `npm test`, then refactoring (probably in #48), creating/extracting an app.stop() method to be called after each test, to instantiate a new app for each test suite.

**Comment by mamen** [comment]
Issue can be closed as we have a coverage of over 80%
