### ISSUE TITLE
Dev Env watch mode: Webpack

### ISSUE THREAD

**Issue by Phoscur** [ugml/api#37]
In development it's tedious to always rebuild and restart by hand, it's possible to do that automagically for filechanges, even hot module reloading only specific modules with webpack. 
Linting can be done within the same watch loop, e.g with [ForkTSChecker](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin)!

Also tests in watchmode are very desirable for a TDD approach and to reach high test coverage (#30).

Add missing npm tasks:
- watch: build with watchmode, restart api server accordingly
- watch-tests: run tests in watchmode

**Comment by mamen** [comment]
i like what you've already done with the grund watch-task in our PR #36 

could you make it so, that the watch-task also starts up a server and reloads the server when there have been changes?

**Comment by Phoscur** [comment]
Mh, I'd probably throw out Gulp in favor of starting the express server with webpack, but configuring nodemon to watch the build directory to restart the api might be an easier short term solution. 

Webpacks hot module reloading peformance impact will be more interesting as the project grows and desires a combined dev env with the client side (monorepo).

**Comment by Phoscur** [comment]
-> #41 may close this for now
