### ISSUE TITLE
Use mysql2 connection pool with promise support

### ISSUE THREAD

**Issue by Phoscur** [ugml/api#48]
Refactoring to use `pool.promise()`, async/await and **releasing** connections when sending a request response should lead to a working watch mode for tests #30 (yes it does! 2a5abe0386af844ab5a0e0973c378abf040a3011)

```javascript
async function main() {
  // get the client
  const mysql = require('mysql2');
  // create the pool
  const pool = mysql.createPool({host:'localhost', user: 'root', database: 'test'});
  // now get a Promise wrapped instance of that pool
  const promisePool = pool.promise();
  // query database using promises
  const [rows,fields] = await promisePool.query("SELECT 1");
```
https://www.npmjs.com/package/mysql2

**Comment by mamen** [comment]
I've switched our queries to use a connection-pool, but currently without much async/await. This should be refactored for better readability.

**Comment by Phoscur** [comment]
Closing since this has been changed in da6940cac9e2ed06dd37395684de69d734be0ff6 and 9a2682437ff4687d400f14056574042050498211 and is now confirmed to be working.
