### ISSUE TITLE
Consistent position naming

### ISSUE THREAD

**Issue by Phoscur** [ugml/api#56]
I've seen galaxy, system and planet position prefixed with pos and without - something needs to be fixed there!

I'd propose a different approach, encapsulating all three values into a subobject (value object) [see very basic Position with X and Y example](https://github.com/Phoscur/Phlame/blob/master/src/model/Position.js). There could be a family of different position variant classes: G-S-P, G-S-P-inbetween (for ships), and variants of it like I was opening the gates for by uncoupling it. (Why not have a solarsystem each?^^)
The benefit is a truely object oriented logic allowing for all kinds of distance calculations closer to reality.

> This poses the question how adaptable this API wants to be for further developments even beyond OGame base?

My goal would be to push as much as possible into configuration, so the engine just supports "OGame like" experience but is not limited to it. 
Then this also applies to resource(type)s and buildings, ...

I'm not saying I would currently change the SQL model to fit those ideas, but think how you want to shape the API @mamen.

**Comment by mamen** [comment]
I will look into this as soon as possible. Originally, the fields were names "galaxy", "system", and "planet. I later found out, that _system_ is a reserverd keyword within mysql (who would have thought 😂 ) and i've started prefixing these fields with _pos__. But, apparently, I've forgot about some of them.

Regarding your proposal for positioning in general, I'd also like to see different options for positioning within the game. Maybe have circular solar-systems and galaxies? Or have one big universe with just x-y positions like a lot of other games have. But that has to be diskussed :) Also, as you've already said, that could be a configuration thing to allow different systems for different installments of the game.
