### ISSUE TITLE
Engine abstraction and monorepo discussion

### ISSUE THREAD

**Issue by Phoscur** [ugml/api#83]
We have multiple parts, and for now we are off well in performance with v8 and node. But at some point we might want to optimize by rewriting parts in different languages to scale (e.g. Rust, C++, Python). Especially Rust and Webassembly compiliation might be interesting in the context of performance.

If we would organize this in a monorepo we could make a good amount of typescript modules, which could later be replaced one by one, depending on need for optimization.
Packages:
- engine (resources, buildings, fleet)
- server (api, large scale persistence)
- event system
- client (pwa, localstorage) depends on the event system and server for actual information and uses the engine to predict
- communication (microservices? around p2p and notifications: email, chat)  plugs into the event system
- other clients, engines can live aside here or in different repos for more independence

To reference my old engine implementation again, here is another reason why we might need replacement for javascript and it's number format for actual validation:
https://github.com/Phoscur/Phlame/blob/e9bf6271e31dcee18bbcd42a878e717304f2f27a/src/model/resources/Resource.js#L380
```js 
Resource.prototype.epsilonEquals = function(resource, epsilon) {
    return resource instanceof Resource
            && this.getType() === resource.getType()
            && Math.abs(this.getAmount() - resource.getAmount()) < epsilon;
};
```
We either need to use an epsilon margin or some other tricks to work with/force actual integers (v8 auto optimization) and be extra careful with small numbers.
To me, this is another reason to put packages even with the same interfaces alongside eachother for dependency injection (JavaScript, TypeScript, WebAssembly).

**Comment by mamen** [comment]
I am still not sure, how we would benefit from a monorepo. Your proposal to implement most things as typescript modules sounds reasonable and I can get behind that idea. But in my opinion, we should still separate the api (or server for that matter) and the clients into different repos. The event system can be within the api-repo until we need to scale it, although I don't see a real benefit here.

This is not a hard no from me, just my thoughts, I am very open to have my opinion changed :grinning: 

The point with error margins could be negated, as you've already said, by using a language designed for precise language operations and support for large numbers (maybe python or even matlab/R?). Although it is questionable, whether an error in the 12th decimal place has a real impact on the game in general.

**Comment by Phoscur** [comment]
You are right, we should try to shave out clear benefits in different aspects here:
- project organization: shared repo means stronger collaboration between the projects
- shared standards
- shared documentation
- full stack in one project: better integration
- shared (e2e test & dev) tooling
- full stack in one project: better integration

Actually I don't see any aspects against this. Well okay, there is some work to do to find the right shared standards for collaboration, but in the end that should make both/all of us faster.

The usual arguments for repo separation are ineffective:
- dev env (is way too similar here, the client includes always includes a server)
- language (is the same)
- system separation of concerns (depends on the architecture)

We should just think of it as "the game" (client and server together with shared modules) and benefit from easy collaboration.

The monorepo approach in this will allow for early recognition and separation of performance-critical parts (to be separated into replaceable modules) without the overhead of creating additional repos.

As soon as we start reimplementing things on the serverside in a different (incompatible) language, this discussion should rearise and I'd probably prefer it kept outside at least until maturity.

**Comment by Phoscur** [comment]
Actually, to hang myself up on the last argument, this might need to wait until 1.0.
